<?php

/**
 * @file
 *   Main module file.
 */

define("BORROWS_RESOURCE_CT", "bookingsapi_resource");
define("BORROWS_PREBOOKING_DAYS", "60");

/**
 * Implementation of hook_menu().
 */
function borrows_menu() {
  $items['borrows_ajax'] = array(
    'page callback' => 'borrows_ajax',
    'access arguments' => array('access content'), // @TODO Adjust.
    'type' => MENU_CALLBACK,
  );
  $items['borrows_post'] = array(
    'page callback' => 'borrows_post',
    'access arguments' => array('access content'), // @TODO Adjust.
    'type' => MENU_CALLBACK,
  );

  $items['admin/settings/borrows'] = array(
    'title'            => 'Borrows settings',
    'description'      => 'Configure Borrows module.',
    'access arguments' => array('administer borrows configuration'),
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('borrows_admin_form'),
    'type'             => MENU_NORMAL_ITEM,
    'file'             => 'borrows.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_perm().
 */
function borrows_perm() {
  return array('administer borrows configuration');
}

/**
 * Implementation of hook_calendar_block().
 */
function borrows_calendar_block(&$calendar, &$date, $op) {
  switch($op) {
    case 'load':
      $path = drupal_get_path('module', 'borrows');
      drupal_add_css($path . '/css/borrows.css');
      drupal_add_js($path . '/js/jquery.blockUI.js');
      drupal_add_js($path . '/js/borrows.js', 'module', 'footer');
      drupal_add_js(array('borrows' => borrows_get_settings()), 'setting', 'footer');
      //dpm($calendar);
      break;
    case 'alter':
      //dpm($date);
      //dpm($calendar);

      $is_weekend = in_array($date->weekday, array('sa', 'su'));

      // Do not allow booking for today and tomorrow.
      // strtotime() needs a bit of help.
      $is_allowed = (strtotime($date->day . '-' . $date->month . '-' . $date->year) >= (strtotime('tomorrow') + (24 * 60 * 60)));

      // Convert to hungarian date format to make comparison easy.
      $date_hu = date('Y-m-d', strtotime($date->year . '-' . $date->month . '-' . $date->day));

      // Mark weekday as weekend, if $day is a public holiday.
      if (!$is_weekend) {
        $holidays = explode("\r\n", variable_get('borrows_holidays', NULL));
        if (in_array($date_hu, array_values((array)$holidays))) {
          $is_weekend = TRUE;
        }
      }
      // Remove weekday flag, if $day is a working day.
      if ($is_weekend) {
        $weekends = explode("\r\n", variable_get('borrows_weekends', NULL));
        if (in_array($date_hu, array_values((array)$weekends))) {
          $is_weekend = FALSE;
        }
      }

      // @TODO Implement this using bookingsapi.
      $is_bookable = TRUE;

      if ($is_allowed) {
        if ($is_bookable) {
          $class = 'form-checkbox';
          // Mark weekends with a nice class.
          if ($is_weekend) {
            $class .= ' borrows-weekend';
          }

          $date->content  = '<label class="option" for="' . $date_hu . '">';
          $date->content .= '<input type="checkbox" name="borrowdate[' . $date_hu . ']" value="' . $date_hu . '" id="borrowdate-' . $date_hu. '" class="' . $class . '" />';
          $date->content .= $date->day . '</label>';
        }
        else {
          $date->content = '<span class="borrows-booked">' . $date->day . '</span>';
        }
      }
      break;
  }
}

function borrows_ajax($nid = NULL) {
  if ($node = node_load($nid)) {
    if ($node->type == BORROWS_RESOURCE_CT) {
      $node_allowed_days = $node->field_allowed_days[0]['value'];

      // @TODO implement this using bookingsapi.
      $days_till_next_booking = 30;

      $prebooking = variable_get('borrows_prebooking', BORROWS_PREBOOKING_DAYS);

      $booking_info = array(
        'allowed_days' => min($node_allowed_days, $days_till_next_booking, $prebooking),
      );

      return drupal_json($booking_info);
    }
  }
  return drupal_json();
}

/**
 * Handle the AJAX request.
 */
function borrows_post() {
  //dd($_POST['days']);
  // @TODO Authenticate using the AJAX token.
  /*
  if (!borrows_ajax_auth()) {
    return FALSE;
  }
  */

  // @TODO Consider using only From and To dates.
  $days = json_decode($_POST['days'], TRUE);

  // And here we go.
  $booking = array(
    'resource_id' => 12,
  //  'record_id' => NULL,
    'type' => BOOKINGSAPI_BOOKING,
  //  'values' => array('resource_id' => 12),
    'name' => '[token]',
    'description' => '[token]',
    'start' => '2011-06-16 17:00:00',
    'end' => '2011-06-17 17:00:00',
    'status' => BOOKINGSAPI_STATUS_FINALIZED,
  );

  //$booking_result = bookingsapi_booking_save($booking);

  dd($days);
  print "OK";
  //drupal_goto();
}

function borrows_get_settings() {
  $node = menu_get_object();
  $holidays = explode("\r\n", variable_get('borrows_holidays', NULL));
  $weekends = explode("\r\n", variable_get('borrows_weekends', NULL));
  return array(
    'holidays' => $holidays,
    'weekends' => $weekends,
    'nid' => $node->nid,
    'ajax_path' => url('borrows_post'),
  );
}
