<?php

/**
 * @file
 *   Main module file.
 */


/**
 * Implementation of hook_calendar_block().
 */
function borrows_calendar_block(&$calendar, &$date, $op) {
  switch($op) {
    case 'load':
      drupal_add_css(drupal_get_path('module', 'borrows') . '/css/borrows.css');
      break;
    case 'alter':
      //dpm($date);
      //dpm($calendar);

      $is_weekday = !in_array($date->weekday, array('sa', 'su'));
      // Do not allow booking for today and tomorrow.
      // strtotime() needs a bit of help.
      $is_allowed = (strtotime($date->day . '-' . $date->month . '-' . $date->year) >= (strtotime('tomorrow') + (24 * 60 * 60)));

      if ($is_weekday && $is_allowed) {
        $date->content  = '<label class="option" for="' . $date->date . '">';
        $date->content .= '<input type="checkbox" name="borrowdate[' . $date->date . ']" value="' . $date->date . '" id="borrowdate-' . $date->date . '" class="form-checkbox" />';
        $date->content .= $date->day . '</label>';
      }
      break;
  }
}
